#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server:
# Requirements:
#   Accepts 4 parameters:
#   - The path to the file to be transferred
#   - The IP of the server we want to transfer the file to
#   - The username scp connects with
#   - The path to the SSH private key that scp uses
#   Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed
#   scp must transfer the file to the user home directory ~/
#   Strict host key checking must be disabled when using scp

# check if less than 3 parameters passed
if [ $# -lt 4 ]
then
echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
exit 1
fi

## transfer file to server
# given info for transfer
file_path=$1
IP=$2
userName=$3
privSSH_path=$4

# Strict host key checking disable
# transfers file from client to server using private key
scp -o "StrictHostKeyChecking=no" -i "$privSSH" "$file_path" "$userName@$IP:~/"
