#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page
# that contains the string "Ceci n'est pas une page".

# Update & Install nginx
sudo apt-get update
sudo apt-get install -y nginx


# set the index page to print hello world
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure Nginx server so that /redirect_me redirects users to another page.
newString="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/MA-Abahmane permanent;"

sudo sed -i "s/server_name _;/$newString/" /etc/nginx/sites-enabled/default


# se the 404 error page to display message 
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure the Nginx servers custom 404 page to contain the string Ceci n'est pas une page.
newString="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$newString/" /etc/nginx/sites-enabled/default


# reaload nginx service
sudo service nginx restart
