#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

# - Update package list | Install HAproxy
sudo apt-get update
sudo apt-get install -y haproxy


# - configure HAproxy so that it sends traffic to web-01 and web-02
# write the new configurations into the 'haproxy.cfg'
echo "frontend web-front
        bind *:80
        default_backend web-backend
        
backend web-backend
        balance roundrobin
        server 266807-web-01 34.203.33.172:80 check
        server 266807-web-02 54.210.234.151:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

# restart haproxy service to load out changes
sudo service haproxy start
