#!/usr/bin/env bash
# Create a MySQL dump of all databases and compress it into an archive
passwd="$1"

mysqldump -uroot -p"$passwd" --all-databases > backup.sql && tar -czvf $(date +%d-%m-%Y).tar.gz backup.sql
