#!/usr/bin/env bash
# A Bash script that displays listening ports:
#  - That only shows listening sockets
#  - That shows the PID and name of the program to which each socket belongs
#
# Ports to remember:
#   22 for SSH
#   80 for HTTP
#   443 for HTTPS
netstat -lp
