#!/usr/bin/env bash
# a Bash script that pings an IP address passed as an argument.
IPadress=$1

# check if the IP adress is given
if [ -z "$IPadress" ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# send calls to check if the network device is available on the network
ping -c 5 "$IPadress"
