#!/usr/bin/env bash
# a Bash script that:
# - Creates the file /var/run/myscript.pid containing its PID
# - Displays To infinity and beyond indefinitely
# - Displays I hate the kill command when receiving a SIGTERM signal
# - Displays Y U no love me?! when receiving a SIGINT signal
# - Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
echo $$ > /var/run/myscript.pid

# trap 'kill' and 'pkill' signals
trap 'killed' SIGTERM
killed() {
    echo "I hate the kill command"
    rm -f /var/run/myscript.pid
    exit
}

# trap 'Ctrl + C' signals
trap 'stoped' SIGINT
stoped() {
    echo "Y U no love me?!"
    rm -f /var/run/myscript.pid
    exit
}

i=7 # infinit loop
while [ $i -eq 7 ]
do
    echo "To infinity and beyond"
    sleep 2
done