#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd.
while IFS=: read -r username _ uid _ _ home _
do  
    cmd=$(head -n 1 $home/$username)
    echo "The user $username is part of the $uid gang,
     lives in $home and rides COMMAND/SHELL. USER
      ID's place is protected by the passcode x, more
       info about the user here: $username"
done < /etc/passwd
