#!/usr/bin/env bash
# The file /etc/passwd has already been covered in a previous project and you should be
# familiar with it. Today we will make up a story based on it.
while IFS=: read -r username password Uid gid Uinfo home shell
do
    echo "The user $username is part of the $gid gang,"\
    "lives in $home and rides $shell."\
    "$Uid's place is protected by the passcode $password,"\
    "more info about the user here: $Uinfo"
done < /etc/passwd
