#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd.
while IFS=: read -r username password Uid gid Uinfo home shell
do  
    cmd=$(head -n 1 $home/$username)
    echo "The user $username is part of the $gid gang,"\
    "lives in $home and rides $shell."\
    "$Uid's place is protected by the passcode $password,"\
    "moreinfo about the user here: $Uinfo"
done < /etc/passwd
