#!/usr/bin/env bash
# This script is displaying "Best School" 9 times and Hi 1 time using while loop
i=0
while [ $i -lt 10 ]
do
    echo "Best School"
    if [ $i -eq 8 ]; then
        echo "Hi"
    fi
    i=$((i + 1))
done