#!/usr/bin/env bash
# This script is displaying the state of a the file school

F_name="school"

# check if file exists
if [ -e "$F_name" ]; then
    echo "school file exists"
    # check is file is empty
    if [ -s "$F_name" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    # check is its s regular file
    if [ -f "$F_name" ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi