#!/usr/bin/env bash
# A Bash script that configures an Ubuntu server with the below requirements:
# - localhost resolves to 127.0.0.2
# - facebook.com resolves to 8.8.8.8.
# - The checker is running on Docker, so make sure to read this

# creat a file 'hosts_cpy' in root and save a copy of '/etc/hosts' in it
cp /etc/hosts ~/hosts_cpy

# update the IP adress of 'localhost' to '127.0.0.2'
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts_cpy
# check if the IP adress already exists for 'facebook.com' and is '8.8.8.8'
# if not set; add '8.8.8.8 facebook.com' to the file.
grep -qxF '8.8.8.8 facebook.com' ~/hosts_cpy || echo '8.8.8.8 facebook.com' >> ~/hosts_cpy

# over write the contents of '/etc/hosts' with the update data in '~/hosts_cpy'
cp -f ~/hosts_cpy /etc/hosts
# remove file after use
rm ~/hosts_cpy
