#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user.
pkill "apache2"
sudo sed -i '2i user nginx;' /etc/nginx/nginx.conf
sudo chmod u+rw,g+r,o+r /etc/nginx/nginx.conf
sudo sed -i 's/\<80\>/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
